enable-magisk-update = true
parallel-jobs = 1

patches-version = "dev"

[YouTube-RV]
app-name = "YouTube"
rv-brand = "RV"
build-mode = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"

[Music-RV]
app-name = "Music"
rv-brand = "RV"
build-mode = "both"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
arch = "arm64-v8a"
